export const FETCH_SUB_REDDITS_START = "FETCH_SUB_REDDITS_START";
export const FETCH_SUB_REDDITS_SUCCESS = "FETCH_SUB_REDDITS_SUCCESS";
export const FETCH_SUB_REDDITS_FAILURE = "FETCH_SUB_REDDITS_FAILURE";
